version: 1
disable_existing_loggers: False

formatters:
  default:
    format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  access:
    format: "[%(asctime)s] %(message)s"

handlers:
  app_file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: logs/app.log
    encoding: utf8
    mode: a

  error_file_handler:
    class: logging.FileHandler
    level: WARNING
    formatter: default
    filename: logs/error.log
    encoding: utf8
    mode: a

  access_file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: access
    filename: logs/access.log
    encoding: utf8
    mode: a

loggers:
  access_logger:
    level: INFO
    handlers: [access_file_handler]
    propagate: no

root:
  level: DEBUG
  handlers: [app_file_handler, error_file_handler]
